- name: Install debian base packages
  apt: name={{item}} state=installed
  with_items:
    - htop
    - vim
    - python
    - build-essential
    - screen
    - fail2ban

- name: Install homie specific packages
  apt: name={{item}} state=installed
  with_items:
    - nginx
    - libxslt-dev
    - libxml2-dev
    - python3
    - python3-venv
    - python3-pip
    - python3-lxml
