- name: add mosquitto repo
  copy:
    src: "{{role_path}}/files/mosquitto-jessie.list"
    dest: "{{apt.listd}}/mosquitto-jessie.list"
    owner: root
    group: root
    mode: 0644
  notify:
    - "apt update"

- name: install mosquitto from repo
  apt:
    name: mosquitto
