- copy:
    src: "{{ role_path }}/files/configuration.yaml"
    dest: /home/homeassistant/.homeassistant/configuration.yaml
    owner: homeassistant
    group: homeassistant
    mode: 774
  notify:
    - "restart home-assistant"
- copy:
    src: "{{ role_path }}/files/configs/"
    dest: /home/homeassistant/.homeassistant/configs/
    owner: homeassistant
    group: homeassistant
    mode: 774
  notify:
    - "restart home-assistant"
