- name: Install prequisites
  apt: name={{item}} state=installed
  with_items:
    - libfontconfig
    - adduser
  tags:
    - install

- name: check if deb was already downloaded
  stat:
    path: "{{grafana.deb_file}}"
  register: grafana_downloaded
  tags:
    - install

- name: Download packages
  get_url:
    url: "https://github.com/fg2it/grafana-on-raspberry/releases/download/v4.1.2/grafana_4.1.2-1487023783_armhf.deb"
    dest: "{{grafana.deb_file}}"
    mode: 0774
  when: grafana_downloaded.stat.exists == False
  tags:
    - install


- name: Install grafana
  apt:
    deb: "{{grafana.deb_file}}"
  tags:
    - install
