homeassistant:
  name: homie.k3wl.de
  latitude: 49.157382
  longitude: 8.634601
  elevation: 125
  unit_system: metric
  time_zone: CET

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

http: !include configs/http-passwords.yml

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

notify mails: !include configs/notification-by-mail.yml

# View all events in a logbook
logbook:

# Track the sun
sun:

# sensors
sensor:
  - platform: yr

# Text to speech
tts:
  platform: google

# Device Tracking
device_tracker:
- platform: fritz
  host: 192.168.178.1

# mqtt
mqtt:
  broker: localhost
  port: 1883
  client_id: homie-1
  keepalive: 60
  protocol: 3.1
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 1
    retain: true
  will_message:
    topic: 'hass/status'
    payload: 'offline'
    qos: 1
    retain: true
